// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqrgqevteccqxnrmocuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxcmdxZXZ0ZWNjcXhucm1vY3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODY1NDMsImV4cCI6MjA2MTE2MjU0M30.C9XKbuFbQT0rh_NHx7quxGhG7-FWWQp1gobfK3i6-1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);